#!/bin/sh

loops=$1
shift

for i in $( seq 0 $loops ); do
  start=`date +%s%N`

  str="$*"
  eval $str 2>&1 > /dev/null

  end=`date +%s%N`
  elapsed=`echo "scale=8; ($end - $start) / 1000000" | bc`
  echo "$i\t$elapsed ms"
done