#!/bin/bash

suites=$(find -name *.java | xargs grep -l @Suite)
testcases=$(find -name *.java | xargs grep -l @Test)

for i in $(cat testcases); do
  fileName=$(basename $i)
  className=${fileName/.java}
  
  if ! grep -q $className $suites; then
    echo $className
  fi
done