#! /usr/bin/awk -f

/connection received/ {
  timestamp=gensub(/^([0-9]{4}(-[0-9]{2}){2} ([0-9]{2}:[0-9]))[0-9]:[0-9]*/, "\\1", "g", $1" "$2)
  con[timestamp] += 1
}

/disconnection: session time/ {
  timestamp=gensub(/^([0-9]{4}(-[0-9]{2}){2} ([0-9]{2}:[0-9]))[0-9]:[0-9]*/, "\\1", "g", $1" "$2)
  dis[timestamp] += 1
}


END {
for (timestamp in con) {
    print timestamp, con[timestamp], dis[timestamp] | "sort" 
  }
}