#!/bin/sh

cmd=""

if [ -z "$1" ]; then
  echo "default command"
  cmd="pull -u"
else
  cmd=$@
fi

echo "  hg $cmd"

DIR=$(basename $(pwd))

if [ "$DIR" != "modules" ]
then
  echo "warn: mods should be used inside the modules directory"
fi

for i in *; do
	if [ -e "$i/.hg" ]
	then
		echo ">>> $i"
		cd $i
		eval "hg $cmd"
		cd ..
	fi
done
