#!/bin/bash

path=$(dirname "$(readlink -f "$0")")

echo 'new DalConnectionProvider() with flush'
$path/diff-dir-text $1 $2 '>.*new DalConnectionProvider()' java

echo
echo '*****************'
echo 'js with "'
$path/diff-dir-text $1 $2 '>.*"' js

echo
echo '*****************'
echo 'Updated copyright'
$path/copyright $1 $2