#! /usr/bin/awk -f

BEGIN {
  OFS="\t"
  SLOW=100
  print "timestamp", "slower than " SLOW " ms", "total"
} 

{
  respTimeMs=$14/1000

  # grouping time per minute
  timestamp=gensub(/.*:([0-9]*:[0-9]*):[0-9]*/, "\\1", "g", $4)

  cnt[timestamp] += 1
  if (respTimeMs > 100) {
    slow[timestamp] += 1
  }


# print timestamp
}

END {
  for (t in cnt) {
    s = slow[t]?slow[t]:0
    print t, s, cnt[t] | "sort"
  }
}

