#! /usr/bin/awk -f



{
  reqSize=$13
  respTime=$14

 # normalize url -> remove all query string (after ?)
  
  url = $9
  if (url ~ /org.openbravo.client.kernel/) {
    url = "[AH] " gensub(/.*_action=(.*)/,"\\1", "g", url)
  } 

  url=gensub(/([^?%]*).*/,"\\1", "g", url)
  

  cnt[url]+=1; 
  uploadedBytes[url]+=reqSize; 
  time[url]+=respTime

 # print url, $13, $14
}

END {
  OFS="\t"

  print "\n== Top number of requests =="

  for (u in cnt) {
    print cnt[u], time[u]/1000000, u | "sort -rn"
  }
  
} 



