#! /usr/bin/awk -f

# Groups requests per minute from apache's access log printing:
#  * number of requests
#  * avg uploaded bytes per request
#  * avg response time per requst
#
# assuming acces log formatted as:
# "%h %l %u %t %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %>s %b %I %D \"%{Referer}i\" \"%{User-agent}i\""
# 
# usage: req-per-minute ssl_access.log

BEGIN {
  OFS="\t"
  print "Timestamp","Request count", "Avg request size (bytes)", "Avg response time (ms)"
} 

{
  # grouping time per minute
  timestamp=gensub(/.*:([0-9]*:[0-9]*):[0-9]*/, "\\1", "g", $4) 
  reqSize=$13
  respTime=$14

 # no needed here!
 # # normalize url -> remove all query string (after ?)
 # url=gensub(/(.*)\?.*/,"\\1", "g", $9)

  cnt[timestamp]+=1; 
  uploadedBytes[timestamp]+=reqSize; 
  time[timestamp]+=respTime

 # print timestamp, url, $13, $14
}

END {
  for (url in cnt) {
    reqs = cnt[url]
    print url, reqs, uploadedBytes[reqs]/reqs, time[reqs]/(reqs*1000) | "sort" 
  }
}
