#!/bin/bash

for ws in $*; do
  echo "Looking for Openbravo.properties in $ws"
 
  obProps=$ws/openbravo/config/Openbravo.properties
  if [ ! -f "$obProps" ]; then
    obProps=$(find $ws -wholename "*/config/Openbravo.properties")
  fi

  if [ -n "$obProps" ] && [ -f "$obProps" ]; then
    echo "Found Openbravo properties: $obProps"
    
    dbName=$(awk -F = '/^bbdd.sid/ {print $2}' $obProps)
    dbUser=$(awk -F = '/^bbdd.systemUser/ {print $2}' $obProps)
    dbPass=$(awk -F = '/^bbdd.systemPassward/ {print $2}' $obProps)
    dbPort=$(awk -F = '/^bbdd.url/ {print $2}' $obProps | sed 's/.*:\([0-9]*\)/\1/')
    
    echo "dropping database $dbName"
    
    echo "drop database $dbName;"
    PGPASSWORD=$dbPass psql -U $dbUser -h localhost -p $dbPort -t -c "drop database $dbName;" 2>&1 ;
  else
    echo "Not found Openbravo properties for $ws"
  fi

  echo "deleting ws $ws"
  rm -rf $ws
done