#!/bin/sh

cmd=""

if [ -z "$1" ]; then
  echo "default command"
  cmd="pull -u"
else
  cmd=$@
fi

echo "  hg/git $cmd"

dir=$(basename $(pwd))

if [ "$dir" != "modules" ]; then
  echo "warn: mods should be used inside the modules directory"
fi

for i in *; do
  if [ -e "$i/.hg" ]; then
    echo ">>> hg repo: $i"
    cd $i
    eval "hg $cmd"
    cd ..
  elif [ -e "$i/.git" ]; then
    echo ">>> git repo: $i"
    cd $i
    eval "git $cmd"
    cd ..
  fi
done
